services:
    app:
        container_name: 'express-tdd'
        build:
            context: .
            dockerfile: Dockerfile
        command: pnpm run start
        env_file:
            - '.env'
        ports:
            - '3000:3000'
        volumes:
            - '.:/src/app'
        depends_on:
            - db
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - v_socialdb:/var/lib/mysql
        ports:
            - ${DB_PORT}:${DB_PORT}

volumes:
    v_socialdb:
